# Generated by Django 4.1.3 on 2022-12-09 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='countvehicles',
            name='video_output',
            field=models.FileField(blank=True, max_length=255, upload_to='videos/'),
        ),
    ]
