# Generated by Django 3.2.7 on 2022-12-26 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_countvehicles_video_output'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countvehicles',
            name='count',
        ),
        migrations.AlterField(
            model_name='countvehicles',
            name='video_output',
            field=models.FileField(blank=True, max_length=255, upload_to='output/'),
        ),
    ]
